### ISSUE TITLE
Can you please explain what these values are?

### ISSUE THREAD

**Issue by BrianGilbert** [fogleman/pack3d#3]
https://github.com/fogleman/pack3d/blob/2c30ae96c6b2f6efd44c17c58e8dcb4bc81b6c9e/cmd/binpack/main.go#L48-L49

I'm currently making the assumption that P is the spacing between a part and the boundry of the next part (essentially making space between parts 5mm?), but I am unsure what S is for, can you please help?

**Comment by fogleman** [comment]
P is one half the spacing between parts. (Each model is padded that much so it gets doubled.)

`binpack` works with integer coordinates. S scales up floats by a factor of 100 here before casting to an int.

**Comment by BrianGilbert** [comment]
@fogleman thanks, no reason we'd want to change the S value then as far as I can see.
